TEMPLATE=subdirs
SUBDIRS += \
    LibPNG.pro

#TEMPLATE = lib
#CONFIG+=staticlib


INCLUDEPATH+=trunk/Source/LibPNG/ \
trunk/Source/LibRawLite/ \

SOURCES += \
    FreeImageLibCreator.cpp \
    trunk/Source/LibPNG/example.c \
    trunk/Source/LibPNG/png.c \
    trunk/Source/LibPNG/pngerror.c \
    trunk/Source/LibPNG/pngget.c \
    trunk/Source/LibPNG/pngmem.c \
    trunk/Source/LibPNG/pngpread.c \
    trunk/Source/LibPNG/pngread.c \
    trunk/Source/LibPNG/pngrio.c \
    trunk/Source/LibPNG/pngrtran.c \
    trunk/Source/LibPNG/pngrutil.c \
    trunk/Source/LibPNG/pngset.c \
    trunk/Source/LibPNG/pngtest.c \
    trunk/Source/LibPNG/pngtrans.c \
    trunk/Source/LibPNG/pngwio.c \
    trunk/Source/LibPNG/pngwrite.c \
    trunk/Source/LibPNG/pngwtran.c \
    trunk/Source/LibPNG/pngwutil.c \
    trunk/Source/LibRawLite/src/decoders/canon_600.cpp \
    trunk/Source/LibRawLite/src/decoders/crx.cpp \
    trunk/Source/LibRawLite/src/decoders/decoders_dcraw.cpp \
    trunk/Source/LibRawLite/src/decoders/decoders_libraw.cpp \
    trunk/Source/LibRawLite/src/decoders/decoders_libraw_dcrdefs.cpp \
    trunk/Source/LibRawLite/src/decoders/dng.cpp \
    trunk/Source/LibRawLite/src/decoders/fp_dng.cpp \
    trunk/Source/LibRawLite/src/decoders/fuji_compressed.cpp \
    trunk/Source/LibRawLite/src/decoders/generic.cpp \
    trunk/Source/LibRawLite/src/decoders/kodak_decoders.cpp \
    trunk/Source/LibRawLite/src/decoders/load_mfbacks.cpp \
    trunk/Source/LibRawLite/src/decoders/smal.cpp \
    trunk/Source/LibRawLite/src/decoders/unpack.cpp \
    trunk/Source/LibRawLite/src/decoders/unpack_thumb.cpp \
    trunk/Source/LibRawLite/src/demosaic/aahd_demosaic.cpp \
    trunk/Source/LibRawLite/src/demosaic/ahd_demosaic.cpp \
    trunk/Source/LibRawLite/src/demosaic/dcb_demosaic.cpp \
    trunk/Source/LibRawLite/src/demosaic/dht_demosaic.cpp \
    trunk/Source/LibRawLite/src/demosaic/misc_demosaic.cpp \
    trunk/Source/LibRawLite/src/demosaic/xtrans_demosaic.cpp \
    trunk/Source/LibRawLite/src/integration/dngsdk_glue.cpp \
    trunk/Source/LibRawLite/src/integration/rawspeed_glue.cpp \
    trunk/Source/LibRawLite/src/libraw_c_api.cpp \
    trunk/Source/LibRawLite/src/libraw_cxx.cpp \
    trunk/Source/LibRawLite/src/libraw_datastream.cpp \
    trunk/Source/LibRawLite/src/libraw_fuji_compressed.cpp \
    trunk/Source/LibRawLite/src/libraw_xtrans_compressed.cpp \
    trunk/Source/LibRawLite/src/metadata/adobepano.cpp \
    trunk/Source/LibRawLite/src/metadata/canon.cpp \
    trunk/Source/LibRawLite/src/metadata/ciff.cpp \
    trunk/Source/LibRawLite/src/metadata/cr3_parser.cpp \
    trunk/Source/LibRawLite/src/metadata/epson.cpp \
    trunk/Source/LibRawLite/src/metadata/exif_gps.cpp \
    trunk/Source/LibRawLite/src/metadata/fuji.cpp \
    trunk/Source/LibRawLite/src/metadata/hasselblad_model.cpp \
    trunk/Source/LibRawLite/src/metadata/identify.cpp \
    trunk/Source/LibRawLite/src/metadata/identify_tools.cpp \
    trunk/Source/LibRawLite/src/metadata/kodak.cpp \
    trunk/Source/LibRawLite/src/metadata/leica.cpp \
    trunk/Source/LibRawLite/src/metadata/makernotes.cpp \
    trunk/Source/LibRawLite/src/metadata/mediumformat.cpp \
    trunk/Source/LibRawLite/src/metadata/minolta.cpp \
    trunk/Source/LibRawLite/src/metadata/misc_parsers.cpp \
    trunk/Source/LibRawLite/src/metadata/nikon.cpp \
    trunk/Source/LibRawLite/src/metadata/normalize_model.cpp \
    trunk/Source/LibRawLite/src/metadata/olympus.cpp \
    trunk/Source/LibRawLite/src/metadata/p1.cpp \
    trunk/Source/LibRawLite/src/metadata/pentax.cpp \
    trunk/Source/LibRawLite/src/metadata/samsung.cpp \
    trunk/Source/LibRawLite/src/metadata/sony.cpp \
    trunk/Source/LibRawLite/src/metadata/tiff.cpp \
    trunk/Source/LibRawLite/src/postprocessing/aspect_ratio.cpp \
    trunk/Source/LibRawLite/src/postprocessing/dcraw_process.cpp \
    trunk/Source/LibRawLite/src/postprocessing/mem_image.cpp \
    trunk/Source/LibRawLite/src/postprocessing/postprocessing_aux.cpp \
    trunk/Source/LibRawLite/src/postprocessing/postprocessing_ph.cpp \
    trunk/Source/LibRawLite/src/postprocessing/postprocessing_utils.cpp \
    trunk/Source/LibRawLite/src/postprocessing/postprocessing_utils_dcrdefs.cpp \
    trunk/Source/LibRawLite/src/preprocessing/ext_preprocess.cpp \
    trunk/Source/LibRawLite/src/preprocessing/preprocessing_ph.cpp \
    trunk/Source/LibRawLite/src/preprocessing/raw2image.cpp \
    trunk/Source/LibRawLite/src/preprocessing/subtract_black.cpp \
    trunk/Source/LibRawLite/src/tables/cameralist.cpp \
    trunk/Source/LibRawLite/src/tables/colorconst.cpp \
    trunk/Source/LibRawLite/src/tables/colordata.cpp \
    trunk/Source/LibRawLite/src/tables/wblists.cpp \
    trunk/Source/LibRawLite/src/utils/curves.cpp \
    trunk/Source/LibRawLite/src/utils/decoder_info.cpp \
    trunk/Source/LibRawLite/src/utils/init_close_utils.cpp \
    trunk/Source/LibRawLite/src/utils/open.cpp \
    trunk/Source/LibRawLite/src/utils/phaseone_processing.cpp \
    trunk/Source/LibRawLite/src/utils/read_utils.cpp \
    trunk/Source/LibRawLite/src/utils/thumb_utils.cpp \
    trunk/Source/LibRawLite/src/utils/utils_dcraw.cpp \
    trunk/Source/LibRawLite/src/utils/utils_libraw.cpp \
    trunk/Source/LibRawLite/src/write/apply_profile.cpp \
    trunk/Source/LibRawLite/src/write/file_write.cpp \
    trunk/Source/LibRawLite/src/write/tiff_writer.cpp \
    trunk/Source/LibRawLite/src/write/write_ph.cpp \
    trunk/Source/LibRawLite/src/x3f/x3f_parse_process.cpp \
    trunk/Source/LibRawLite/src/x3f/x3f_utils_patched.cpp \
    trunk/Source/LibTIFF4/mkg3states.c \
    trunk/Source/LibTIFF4/mkspans.c \
    trunk/Source/LibTIFF4/tif_aux.c \
    trunk/Source/LibTIFF4/tif_close.c \
    trunk/Source/LibTIFF4/tif_codec.c \
    trunk/Source/LibTIFF4/tif_color.c \
    trunk/Source/LibTIFF4/tif_compress.c \
    trunk/Source/LibTIFF4/tif_dir.c \
    trunk/Source/LibTIFF4/tif_dirinfo.c \
    trunk/Source/LibTIFF4/tif_dirread.c \
    trunk/Source/LibTIFF4/tif_dirwrite.c \
    trunk/Source/LibTIFF4/tif_dumpmode.c \
    trunk/Source/LibTIFF4/tif_error.c \
    trunk/Source/LibTIFF4/tif_extension.c \
    trunk/Source/LibTIFF4/tif_fax3.c \
    trunk/Source/LibTIFF4/tif_fax3sm.c \
    trunk/Source/LibTIFF4/tif_flush.c \
    trunk/Source/LibTIFF4/tif_getimage.c \
    trunk/Source/LibTIFF4/tif_jbig.c \
    trunk/Source/LibTIFF4/tif_jpeg.c \
    trunk/Source/LibTIFF4/tif_jpeg_12.c \
    trunk/Source/LibTIFF4/tif_lerc.c \
    trunk/Source/LibTIFF4/tif_luv.c \
    trunk/Source/LibTIFF4/tif_lzma.c \
    trunk/Source/LibTIFF4/tif_lzw.c \
    trunk/Source/LibTIFF4/tif_next.c \
    trunk/Source/LibTIFF4/tif_ojpeg.c \
    trunk/Source/LibTIFF4/tif_open.c \
    trunk/Source/LibTIFF4/tif_packbits.c \
    trunk/Source/LibTIFF4/tif_pixarlog.c \
    trunk/Source/LibTIFF4/tif_predict.c \
    trunk/Source/LibTIFF4/tif_print.c \
    trunk/Source/LibTIFF4/tif_read.c \
    trunk/Source/LibTIFF4/tif_stream.cxx \
    trunk/Source/LibTIFF4/tif_strip.c \
    trunk/Source/LibTIFF4/tif_swab.c \
    trunk/Source/LibTIFF4/tif_thunder.c \
    trunk/Source/LibTIFF4/tif_tile.c \
    trunk/Source/LibTIFF4/tif_unix.c \
    trunk/Source/LibTIFF4/tif_version.c \
    trunk/Source/LibTIFF4/tif_vms.c \
    trunk/Source/LibTIFF4/tif_warning.c \
    trunk/Source/LibTIFF4/tif_webp.c \
    trunk/Source/LibTIFF4/tif_win32.c \
    trunk/Source/LibTIFF4/tif_wince.c \
    trunk/Source/LibTIFF4/tif_write.c \
    trunk/Source/LibTIFF4/tif_zip.c \
    trunk/Source/LibTIFF4/tif_zstd.c \
    trunk/Source/LibWebP/src/dec/alpha_dec.c \
    trunk/Source/LibWebP/src/dec/buffer_dec.c \
    trunk/Source/LibWebP/src/dec/frame_dec.c \
    trunk/Source/LibWebP/src/dec/idec_dec.c \
    trunk/Source/LibWebP/src/dec/io_dec.c \
    trunk/Source/LibWebP/src/dec/quant_dec.c \
    trunk/Source/LibWebP/src/dec/tree_dec.c \
    trunk/Source/LibWebP/src/dec/vp8_dec.c \
    trunk/Source/LibWebP/src/dec/vp8l_dec.c \
    trunk/Source/LibWebP/src/dec/webp_dec.c \
    trunk/Source/LibWebP/src/demux/anim_decode.c \
    trunk/Source/LibWebP/src/demux/demux.c \
    trunk/Source/LibWebP/src/dsp/alpha_processing.c \
    trunk/Source/LibWebP/src/dsp/alpha_processing_mips_dsp_r2.c \
    trunk/Source/LibWebP/src/dsp/alpha_processing_neon.c \
    trunk/Source/LibWebP/src/dsp/alpha_processing_sse2.c \
    trunk/Source/LibWebP/src/dsp/alpha_processing_sse41.c \
    trunk/Source/LibWebP/src/dsp/cost.c \
    trunk/Source/LibWebP/src/dsp/cost_mips32.c \
    trunk/Source/LibWebP/src/dsp/cost_mips_dsp_r2.c \
    trunk/Source/LibWebP/src/dsp/cost_neon.c \
    trunk/Source/LibWebP/src/dsp/cost_sse2.c \
    trunk/Source/LibWebP/src/dsp/cpu.c \
    trunk/Source/LibWebP/src/dsp/dec.c \
    trunk/Source/LibWebP/src/dsp/dec_clip_tables.c \
    trunk/Source/LibWebP/src/dsp/dec_mips32.c \
    trunk/Source/LibWebP/src/dsp/dec_mips_dsp_r2.c \
    trunk/Source/LibWebP/src/dsp/dec_msa.c \
    trunk/Source/LibWebP/src/dsp/dec_neon.c \
    trunk/Source/LibWebP/src/dsp/dec_sse2.c \
    trunk/Source/LibWebP/src/dsp/dec_sse41.c \
    trunk/Source/LibWebP/src/dsp/enc.c \
    trunk/Source/LibWebP/src/dsp/enc_avx2.c \
    trunk/Source/LibWebP/src/dsp/enc_mips32.c \
    trunk/Source/LibWebP/src/dsp/enc_mips_dsp_r2.c \
    trunk/Source/LibWebP/src/dsp/enc_msa.c \
    trunk/Source/LibWebP/src/dsp/enc_neon.c \
    trunk/Source/LibWebP/src/dsp/enc_sse2.c \
    trunk/Source/LibWebP/src/dsp/enc_sse41.c \
    trunk/Source/LibWebP/src/dsp/filters.c \
    trunk/Source/LibWebP/src/dsp/filters_mips_dsp_r2.c \
    trunk/Source/LibWebP/src/dsp/filters_msa.c \
    trunk/Source/LibWebP/src/dsp/filters_neon.c \
    trunk/Source/LibWebP/src/dsp/filters_sse2.c \
    trunk/Source/LibWebP/src/dsp/lossless.c \
    trunk/Source/LibWebP/src/dsp/lossless_enc.c \
    trunk/Source/LibWebP/src/dsp/lossless_enc_mips32.c \
    trunk/Source/LibWebP/src/dsp/lossless_enc_mips_dsp_r2.c \
    trunk/Source/LibWebP/src/dsp/lossless_enc_msa.c \
    trunk/Source/LibWebP/src/dsp/lossless_enc_neon.c \
    trunk/Source/LibWebP/src/dsp/lossless_enc_sse2.c \
    trunk/Source/LibWebP/src/dsp/lossless_enc_sse41.c \
    trunk/Source/LibWebP/src/dsp/lossless_mips_dsp_r2.c \
    trunk/Source/LibWebP/src/dsp/lossless_msa.c \
    trunk/Source/LibWebP/src/dsp/lossless_neon.c \
    trunk/Source/LibWebP/src/dsp/lossless_sse2.c \
    trunk/Source/LibWebP/src/dsp/lossless_sse41.c \
    trunk/Source/LibWebP/src/dsp/rescaler.c \
    trunk/Source/LibWebP/src/dsp/rescaler_mips32.c \
    trunk/Source/LibWebP/src/dsp/rescaler_mips_dsp_r2.c \
    trunk/Source/LibWebP/src/dsp/rescaler_msa.c \
    trunk/Source/LibWebP/src/dsp/rescaler_neon.c \
    trunk/Source/LibWebP/src/dsp/rescaler_sse2.c \
    trunk/Source/LibWebP/src/dsp/ssim.c \
    trunk/Source/LibWebP/src/dsp/ssim_sse2.c \
    trunk/Source/LibWebP/src/dsp/upsampling.c \
    trunk/Source/LibWebP/src/dsp/upsampling_mips_dsp_r2.c \
    trunk/Source/LibWebP/src/dsp/upsampling_msa.c \
    trunk/Source/LibWebP/src/dsp/upsampling_neon.c \
    trunk/Source/LibWebP/src/dsp/upsampling_sse2.c \
    trunk/Source/LibWebP/src/dsp/upsampling_sse41.c \
    trunk/Source/LibWebP/src/dsp/yuv.c \
    trunk/Source/LibWebP/src/dsp/yuv_mips32.c \
    trunk/Source/LibWebP/src/dsp/yuv_mips_dsp_r2.c \
    trunk/Source/LibWebP/src/dsp/yuv_neon.c \
    trunk/Source/LibWebP/src/dsp/yuv_sse2.c \
    trunk/Source/LibWebP/src/dsp/yuv_sse41.c \
    trunk/Source/LibWebP/src/enc/alpha_enc.c \
    trunk/Source/LibWebP/src/enc/analysis_enc.c \
    trunk/Source/LibWebP/src/enc/backward_references_cost_enc.c \
    trunk/Source/LibWebP/src/enc/backward_references_enc.c \
    trunk/Source/LibWebP/src/enc/config_enc.c \
    trunk/Source/LibWebP/src/enc/cost_enc.c \
    trunk/Source/LibWebP/src/enc/filter_enc.c \
    trunk/Source/LibWebP/src/enc/frame_enc.c \
    trunk/Source/LibWebP/src/enc/histogram_enc.c \
    trunk/Source/LibWebP/src/enc/iterator_enc.c \
    trunk/Source/LibWebP/src/enc/near_lossless_enc.c \
    trunk/Source/LibWebP/src/enc/picture_csp_enc.c \
    trunk/Source/LibWebP/src/enc/picture_enc.c \
    trunk/Source/LibWebP/src/enc/picture_psnr_enc.c \
    trunk/Source/LibWebP/src/enc/picture_rescale_enc.c \
    trunk/Source/LibWebP/src/enc/picture_tools_enc.c \
    trunk/Source/LibWebP/src/enc/predictor_enc.c \
    trunk/Source/LibWebP/src/enc/quant_enc.c \
    trunk/Source/LibWebP/src/enc/syntax_enc.c \
    trunk/Source/LibWebP/src/enc/token_enc.c \
    trunk/Source/LibWebP/src/enc/tree_enc.c \
    trunk/Source/LibWebP/src/enc/vp8l_enc.c \
    trunk/Source/LibWebP/src/enc/webp_enc.c \
    trunk/Source/LibWebP/src/mux/anim_encode.c \
    trunk/Source/LibWebP/src/mux/muxedit.c \
    trunk/Source/LibWebP/src/mux/muxinternal.c \
    trunk/Source/LibWebP/src/mux/muxread.c \
    trunk/Source/LibWebP/src/utils/bit_reader_utils.c \
    trunk/Source/LibWebP/src/utils/bit_writer_utils.c \
    trunk/Source/LibWebP/src/utils/color_cache_utils.c \
    trunk/Source/LibWebP/src/utils/filters_utils.c \
    trunk/Source/LibWebP/src/utils/huffman_encode_utils.c \
    trunk/Source/LibWebP/src/utils/huffman_utils.c \
    trunk/Source/LibWebP/src/utils/quant_levels_dec_utils.c \
    trunk/Source/LibWebP/src/utils/quant_levels_utils.c \
    trunk/Source/LibWebP/src/utils/random_utils.c \
    trunk/Source/LibWebP/src/utils/rescaler_utils.c \
    trunk/Source/LibWebP/src/utils/thread_utils.c \
    trunk/Source/LibWebP/src/utils/utils.c \
    trunk/Source/Metadata/Exif.cpp \
    trunk/Source/Metadata/FIRational.cpp \
    trunk/Source/Metadata/FreeImageTag.cpp \
    trunk/Source/Metadata/IPTC.cpp \
    trunk/Source/Metadata/TagConversion.cpp \
    trunk/Source/Metadata/TagLib.cpp \
    trunk/Source/Metadata/XTIFF.cpp \
    trunk/Source/OpenEXR/Half/eLut.cpp \
    trunk/Source/OpenEXR/Half/half.cpp \
    trunk/Source/OpenEXR/Half/toFloat.cpp \
    trunk/Source/OpenEXR/Iex/IexBaseExc.cpp \
    trunk/Source/OpenEXR/Iex/IexThrowErrnoExc.cpp \
    trunk/Source/OpenEXR/IexMath/IexMathFloatExc.cpp \
    trunk/Source/OpenEXR/IexMath/IexMathFpu.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfAcesFile.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfB44Compressor.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfBoxAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfCRgbaFile.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfChannelList.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfChannelListAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfChromaticities.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfChromaticitiesAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfCompositeDeepScanLine.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfCompressionAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfCompressor.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfConvert.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfDeepCompositing.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfDeepFrameBuffer.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfDeepImageStateAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfDeepScanLineInputFile.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfDeepScanLineInputPart.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfDeepScanLineOutputFile.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfDeepScanLineOutputPart.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfDeepTiledInputFile.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfDeepTiledInputPart.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfDeepTiledOutputFile.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfDeepTiledOutputPart.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfDoubleAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfDwaCompressor.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfEnvmap.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfEnvmapAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfFastHuf.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfFloatAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfFloatVectorAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfFrameBuffer.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfFramesPerSecond.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfGenericInputFile.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfGenericOutputFile.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfHeader.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfHuf.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfIO.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfInputFile.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfInputPart.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfInputPartData.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfIntAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfKeyCode.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfKeyCodeAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfLineOrderAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfLut.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfMatrixAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfMisc.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfMultiPartInputFile.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfMultiPartOutputFile.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfMultiView.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfOpaqueAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfOutputFile.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfOutputPart.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfOutputPartData.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfPartType.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfPizCompressor.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfPreviewImage.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfPreviewImageAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfPxr24Compressor.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfRational.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfRationalAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfRgbaFile.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfRgbaYca.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfRle.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfRleCompressor.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfScanLineInputFile.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfStandardAttributes.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfStdIO.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfStringAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfStringVectorAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfSystemSpecific.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfTestFile.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfThreading.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfTileDescriptionAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfTileOffsets.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfTiledInputFile.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfTiledInputPart.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfTiledMisc.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfTiledOutputFile.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfTiledOutputPart.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfTiledRgbaFile.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfTimeCode.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfTimeCodeAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfVecAttribute.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfVersion.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfWav.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfZip.cpp \
    trunk/Source/OpenEXR/IlmImf/ImfZipCompressor.cpp \
    trunk/Source/OpenEXR/IlmImf/b44ExpLogTable.cpp \
    trunk/Source/OpenEXR/IlmImf/dwaLookups.cpp \
    trunk/Source/OpenEXR/IlmThread/IlmThread.cpp \
    trunk/Source/OpenEXR/IlmThread/IlmThreadMutex.cpp \
    trunk/Source/OpenEXR/IlmThread/IlmThreadMutexPosix.cpp \
    trunk/Source/OpenEXR/IlmThread/IlmThreadMutexWin32.cpp \
    trunk/Source/OpenEXR/IlmThread/IlmThreadPool.cpp \
    trunk/Source/OpenEXR/IlmThread/IlmThreadPosix.cpp \
    trunk/Source/OpenEXR/IlmThread/IlmThreadSemaphore.cpp \
    trunk/Source/OpenEXR/IlmThread/IlmThreadSemaphorePosix.cpp \
    trunk/Source/OpenEXR/IlmThread/IlmThreadSemaphorePosixCompat.cpp \
    trunk/Source/OpenEXR/IlmThread/IlmThreadSemaphoreWin32.cpp \
    trunk/Source/OpenEXR/IlmThread/IlmThreadWin32.cpp \
    trunk/Source/OpenEXR/Imath/ImathBox.cpp \
    trunk/Source/OpenEXR/Imath/ImathColorAlgo.cpp \
    trunk/Source/OpenEXR/Imath/ImathFun.cpp \
    trunk/Source/OpenEXR/Imath/ImathMatrixAlgo.cpp \
    trunk/Source/OpenEXR/Imath/ImathRandom.cpp \
    trunk/Source/OpenEXR/Imath/ImathShear.cpp \
    trunk/Source/OpenEXR/Imath/ImathVec.cpp \
    trunk/Source/ZLib/adler32.c \
    trunk/Source/ZLib/compress.c \
    trunk/Source/ZLib/crc32.c \
    trunk/Source/ZLib/deflate.c \
    trunk/Source/ZLib/gzclose.c \
    trunk/Source/ZLib/gzlib.c \
    trunk/Source/ZLib/gzread.c \
    trunk/Source/ZLib/gzwrite.c \
    trunk/Source/ZLib/infback.c \
    trunk/Source/ZLib/inffast.c \
    trunk/Source/ZLib/inflate.c \
    trunk/Source/ZLib/inftrees.c \
    trunk/Source/ZLib/trees.c \
    trunk/Source/ZLib/uncompr.c \
    trunk/Source/ZLib/zutil.c \
    trunk/Source/FreeImage/BitmapAccess.cpp \
    trunk/Source/FreeImage/CacheFile.cpp \
    trunk/Source/FreeImage/ColorLookup.cpp \
    trunk/Source/FreeImage/Conversion.cpp \
    trunk/Source/FreeImage/Conversion16_555.cpp \
    trunk/Source/FreeImage/Conversion16_565.cpp \
    trunk/Source/FreeImage/Conversion24.cpp \
    trunk/Source/FreeImage/Conversion32.cpp \
    trunk/Source/FreeImage/Conversion4.cpp \
    trunk/Source/FreeImage/Conversion8.cpp \
    trunk/Source/FreeImage/ConversionFloat.cpp \
    trunk/Source/FreeImage/ConversionRGB16.cpp \
    trunk/Source/FreeImage/ConversionRGBA16.cpp \
    trunk/Source/FreeImage/ConversionRGBAF.cpp \
    trunk/Source/FreeImage/ConversionRGBF.cpp \
    trunk/Source/FreeImage/ConversionType.cpp \
    trunk/Source/FreeImage/ConversionUINT16.cpp \
    trunk/Source/FreeImage/FreeImage.cpp \
    trunk/Source/FreeImage/FreeImageC.c \
    trunk/Source/FreeImage/FreeImageIO.cpp \
    trunk/Source/FreeImage/GetType.cpp \
    trunk/Source/FreeImage/Halftoning.cpp \
    trunk/Source/FreeImage/J2KHelper.cpp \
    trunk/Source/FreeImage/LFPQuantizer.cpp \
    trunk/Source/FreeImage/MNGHelper.cpp \
    trunk/Source/FreeImage/MemoryIO.cpp \
    trunk/Source/FreeImage/MultiPage.cpp \
    trunk/Source/FreeImage/NNQuantizer.cpp \
    trunk/Source/FreeImage/PSDParser.cpp \
    trunk/Source/FreeImage/PixelAccess.cpp \
    trunk/Source/FreeImage/Plugin.cpp \
    trunk/Source/FreeImage/PluginBMP.cpp \
    trunk/Source/FreeImage/PluginCUT.cpp \
    trunk/Source/FreeImage/PluginDDS.cpp \
    trunk/Source/FreeImage/PluginEXR.cpp \
    trunk/Source/FreeImage/PluginG3.cpp \
    trunk/Source/FreeImage/PluginGIF.cpp \
    trunk/Source/FreeImage/PluginHDR.cpp \
    trunk/Source/FreeImage/PluginICO.cpp \
    trunk/Source/FreeImage/PluginIFF.cpp \
    trunk/Source/FreeImage/PluginJ2K.cpp \
    trunk/Source/FreeImage/PluginJNG.cpp \
    trunk/Source/FreeImage/PluginJP2.cpp \
    trunk/Source/FreeImage/PluginJPEG.cpp \
    trunk/Source/FreeImage/PluginJXR.cpp \
    trunk/Source/FreeImage/PluginKOALA.cpp \
    trunk/Source/FreeImage/PluginMNG.cpp \
    trunk/Source/FreeImage/PluginPCD.cpp \
    trunk/Source/FreeImage/PluginPCX.cpp \
    trunk/Source/FreeImage/PluginPFM.cpp \
    trunk/Source/FreeImage/PluginPICT.cpp \
    trunk/Source/FreeImage/PluginPNG.cpp \
    trunk/Source/FreeImage/PluginPNM.cpp \
    trunk/Source/FreeImage/PluginPSD.cpp \
    trunk/Source/FreeImage/PluginRAS.cpp \
    trunk/Source/FreeImage/PluginRAW.cpp \
    trunk/Source/FreeImage/PluginSGI.cpp \
    trunk/Source/FreeImage/PluginTARGA.cpp \
    trunk/Source/FreeImage/PluginTIFF.cpp \
    trunk/Source/FreeImage/PluginWBMP.cpp \
    trunk/Source/FreeImage/PluginWebP.cpp \
    trunk/Source/FreeImage/PluginXBM.cpp \
    trunk/Source/FreeImage/PluginXPM.cpp \
    trunk/Source/FreeImage/TIFFLogLuv.cpp \
    trunk/Source/FreeImage/ToneMapping.cpp \
    trunk/Source/FreeImage/WuQuantizer.cpp \
    trunk/Source/FreeImage/ZLibInterface.cpp \
    trunk/Source/FreeImage/tmoColorConvert.cpp \
    trunk/Source/FreeImage/tmoDrago03.cpp \
    trunk/Source/FreeImage/tmoFattal02.cpp \
    trunk/Source/FreeImage/tmoReinhard05.cpp \
    trunk/Source/FreeImageToolkit/BSplineRotate.cpp \
    trunk/Source/FreeImageToolkit/Background.cpp \
    trunk/Source/FreeImageToolkit/Channels.cpp \
    trunk/Source/FreeImageToolkit/ClassicRotate.cpp \
    trunk/Source/FreeImageToolkit/Colors.cpp \
    trunk/Source/FreeImageToolkit/CopyPaste.cpp \
    trunk/Source/FreeImageToolkit/Display.cpp \
    trunk/Source/FreeImageToolkit/Flip.cpp \
    trunk/Source/FreeImageToolkit/JPEGTransform.cpp \
    trunk/Source/FreeImageToolkit/MultigridPoissonSolver.cpp \
    trunk/Source/FreeImageToolkit/Rescale.cpp \
    trunk/Source/FreeImageToolkit/Resize.cpp \
    trunk/Source/LibJPEG/cdjpeg.c \
    trunk/Source/LibJPEG/cjpeg.c \
    trunk/Source/LibJPEG/ckconfig.c \
    trunk/Source/LibJPEG/djpeg.c \
    trunk/Source/LibJPEG/example.c \
    trunk/Source/LibJPEG/jaricom.c \
    trunk/Source/LibJPEG/jcapimin.c \
    trunk/Source/LibJPEG/jcapistd.c \
    trunk/Source/LibJPEG/jcarith.c \
    trunk/Source/LibJPEG/jccoefct.c \
    trunk/Source/LibJPEG/jccolor.c \
    trunk/Source/LibJPEG/jcdctmgr.c \
    trunk/Source/LibJPEG/jchuff.c \
    trunk/Source/LibJPEG/jcinit.c \
    trunk/Source/LibJPEG/jcmainct.c \
    trunk/Source/LibJPEG/jcmarker.c \
    trunk/Source/LibJPEG/jcmaster.c \
    trunk/Source/LibJPEG/jcomapi.c \
    trunk/Source/LibJPEG/jcparam.c \
    trunk/Source/LibJPEG/jcprepct.c \
    trunk/Source/LibJPEG/jcsample.c \
    trunk/Source/LibJPEG/jctrans.c \
    trunk/Source/LibJPEG/jdapimin.c \
    trunk/Source/LibJPEG/jdapistd.c \
    trunk/Source/LibJPEG/jdarith.c \
    trunk/Source/LibJPEG/jdatadst.c \
    trunk/Source/LibJPEG/jdatasrc.c \
    trunk/Source/LibJPEG/jdcoefct.c \
    trunk/Source/LibJPEG/jdcolor.c \
    trunk/Source/LibJPEG/jddctmgr.c \
    trunk/Source/LibJPEG/jdhuff.c \
    trunk/Source/LibJPEG/jdinput.c \
    trunk/Source/LibJPEG/jdmainct.c \
    trunk/Source/LibJPEG/jdmarker.c \
    trunk/Source/LibJPEG/jdmaster.c \
    trunk/Source/LibJPEG/jdmerge.c \
    trunk/Source/LibJPEG/jdpostct.c \
    trunk/Source/LibJPEG/jdsample.c \
    trunk/Source/LibJPEG/jdtrans.c \
    trunk/Source/LibJPEG/jerror.c \
    trunk/Source/LibJPEG/jfdctflt.c \
    trunk/Source/LibJPEG/jfdctfst.c \
    trunk/Source/LibJPEG/jfdctint.c \
    trunk/Source/LibJPEG/jidctflt.c \
    trunk/Source/LibJPEG/jidctfst.c \
    trunk/Source/LibJPEG/jidctint.c \
    trunk/Source/LibJPEG/jmemansi.c \
    trunk/Source/LibJPEG/jmemdos.c \
    trunk/Source/LibJPEG/jmemmac.c \
    trunk/Source/LibJPEG/jmemmgr.c \
    trunk/Source/LibJPEG/jmemname.c \
    trunk/Source/LibJPEG/jmemnobs.c \
    trunk/Source/LibJPEG/jpegtran.c \
    trunk/Source/LibJPEG/jquant1.c \
    trunk/Source/LibJPEG/jquant2.c \
    trunk/Source/LibJPEG/jutils.c \
    trunk/Source/LibJPEG/rdbmp.c \
    trunk/Source/LibJPEG/rdcolmap.c \
    trunk/Source/LibJPEG/rdgif.c \
    trunk/Source/LibJPEG/rdjpgcom.c \
    trunk/Source/LibJPEG/rdppm.c \
    trunk/Source/LibJPEG/rdrle.c \
    trunk/Source/LibJPEG/rdswitch.c \
    trunk/Source/LibJPEG/rdtarga.c \
    trunk/Source/LibJPEG/transupp.c \
    trunk/Source/LibJPEG/wrbmp.c \
    trunk/Source/LibJPEG/wrgif.c \
    trunk/Source/LibJPEG/wrjpgcom.c \
    trunk/Source/LibJPEG/wrppm.c \
    trunk/Source/LibJPEG/wrrle.c \
    trunk/Source/LibJPEG/wrtarga.c \
    trunk/Source/LibJXR/image/decode/JXRTranscode.c \
    trunk/Source/LibJXR/image/decode/decode.c \
    trunk/Source/LibJXR/image/decode/postprocess.c \
    trunk/Source/LibJXR/image/decode/segdec.c \
    trunk/Source/LibJXR/image/decode/strInvTransform.c \
    trunk/Source/LibJXR/image/decode/strPredQuantDec.c \
    trunk/Source/LibJXR/image/decode/strdec.c \
    trunk/Source/LibJXR/image/decode/strdec_x86.c \
    trunk/Source/LibJXR/image/encode/encode.c \
    trunk/Source/LibJXR/image/encode/segenc.c \
    trunk/Source/LibJXR/image/encode/strFwdTransform.c \
    trunk/Source/LibJXR/image/encode/strPredQuantEnc.c \
    trunk/Source/LibJXR/image/encode/strenc.c \
    trunk/Source/LibJXR/image/encode/strenc_x86.c \
    trunk/Source/LibJXR/image/sys/adapthuff.c \
    trunk/Source/LibJXR/image/sys/image.c \
    trunk/Source/LibJXR/image/sys/perfTimerANSI.c \
    trunk/Source/LibJXR/image/sys/strPredQuant.c \
    trunk/Source/LibJXR/image/sys/strTransform.c \
    trunk/Source/LibJXR/image/sys/strcodec.c \
    trunk/Source/LibJXR/jxrgluelib/JXRGlue.c \
    trunk/Source/LibJXR/jxrgluelib/JXRGlueJxr.c \
    trunk/Source/LibJXR/jxrgluelib/JXRGluePFC.c \
    trunk/Source/LibJXR/jxrgluelib/JXRMeta.c \
    trunk/Source/LibOpenJPEG/bio.c \
    trunk/Source/LibOpenJPEG/cidx_manager.c \
    trunk/Source/LibOpenJPEG/cio.c \
    trunk/Source/LibOpenJPEG/dwt.c \
    trunk/Source/LibOpenJPEG/event.c \
    trunk/Source/LibOpenJPEG/function_list.c \
    trunk/Source/LibOpenJPEG/image.c \
    trunk/Source/LibOpenJPEG/invert.c \
    trunk/Source/LibOpenJPEG/j2k.c \
    trunk/Source/LibOpenJPEG/jp2.c \
    trunk/Source/LibOpenJPEG/mct.c \
    trunk/Source/LibOpenJPEG/mqc.c \
    trunk/Source/LibOpenJPEG/openjpeg.c \
    trunk/Source/LibOpenJPEG/opj_clock.c \
    trunk/Source/LibOpenJPEG/phix_manager.c \
    trunk/Source/LibOpenJPEG/pi.c \
    trunk/Source/LibOpenJPEG/ppix_manager.c \
    trunk/Source/LibOpenJPEG/raw.c \
    trunk/Source/LibOpenJPEG/t1.c \
    trunk/Source/LibOpenJPEG/t1_generate_luts.c \
    trunk/Source/LibOpenJPEG/t2.c \
    trunk/Source/LibOpenJPEG/tcd.c \
    trunk/Source/LibOpenJPEG/tgt.c \
    trunk/Source/LibOpenJPEG/thix_manager.c \
    trunk/Source/LibOpenJPEG/tpix_manager.c

DISTFILES += \
    trunk/Dist/delete.me \
    trunk/FreeImage.2017.sln \
    trunk/README.iphone \
    trunk/README.linux \
    trunk/README.md \
    trunk/README.minGW \
    trunk/README.osx \
    trunk/README.solaris \
    trunk/Source/LibJPEG/LibJPEG.2017.vcxproj \
    trunk/Source/LibJPEG/LibJPEG.2017.vcxproj.filters \
    trunk/Source/LibJPEG/README \
    trunk/Source/LibJXR/LICENCE \
    trunk/Source/LibJXR/README \
    trunk/Source/LibOpenJPEG/AUTHORS \
    trunk/Source/LibOpenJPEG/INSTALL \
    trunk/Source/LibOpenJPEG/LICENSE \
    trunk/Source/LibOpenJPEG/NEWS \
    trunk/Source/LibOpenJPEG/README \
    trunk/Source/LibOpenJPEG/THANKS \
    trunk/Source/LibPNG/ANNOUNCE \
    trunk/Source/LibPNG/AUTHORS \
    trunk/Source/LibPNG/CHANGES \
    trunk/Source/LibPNG/INSTALL \
    trunk/Source/LibPNG/LICENSE \
    trunk/Source/LibPNG/README \
    trunk/Source/LibPNG/TODO \
    trunk/Source/LibPNG/configure \
    trunk/Source/LibPNG/png.5 \
    trunk/Source/LibRawLite/COPYRIGHT \
    trunk/Source/LibRawLite/DEVELOPER-NOTES \
    trunk/Source/LibRawLite/LICENSE.CDDL \
    trunk/Source/LibRawLite/LICENSE.LGPL \
    trunk/Source/LibRawLite/README \
    trunk/Source/LibRawLite/README.cmake \
    trunk/Source/LibRawLite/README.demosaic-packs \
    trunk/Source/LibRawLite/README.md \
    trunk/Source/LibTIFF4/COPYRIGHT \
    trunk/Source/LibTIFF4/ChangeLog \
    trunk/Source/LibTIFF4/RELEASE-DATE \
    trunk/Source/LibTIFF4/VERSION \
    trunk/Source/LibTIFF4/tiffvers.h.in \
    trunk/Source/LibWebP/AUTHORS \
    trunk/Source/LibWebP/COPYING \
    trunk/Source/LibWebP/ChangeLog \
    trunk/Source/LibWebP/NEWS \
    trunk/Source/LibWebP/PATENTS \
    trunk/Source/LibWebP/README \
    trunk/Source/LibWebP/README.mux \
    trunk/Source/OpenEXR/Copyrights/ilmbase/AUTHORS \
    trunk/Source/OpenEXR/Copyrights/ilmbase/COPYING \
    trunk/Source/OpenEXR/Copyrights/ilmbase/ChangeLog \
    trunk/Source/OpenEXR/Copyrights/ilmbase/INSTALL \
    trunk/Source/OpenEXR/Copyrights/ilmbase/LICENSE \
    trunk/Source/OpenEXR/Copyrights/ilmbase/NEWS \
    trunk/Source/OpenEXR/Copyrights/ilmbase/README \
    trunk/Source/OpenEXR/Copyrights/ilmbase/README.CVS \
    trunk/Source/OpenEXR/Copyrights/ilmbase/README.OSX \
    trunk/Source/OpenEXR/Copyrights/ilmbase/README.git \
    trunk/Source/OpenEXR/Copyrights/ilmbase/README.namespacing \
    trunk/Source/OpenEXR/Copyrights/ilmbase/README.win32 \
    trunk/Source/OpenEXR/Copyrights/openexr/AUTHORS \
    trunk/Source/OpenEXR/Copyrights/openexr/COPYING \
    trunk/Source/OpenEXR/Copyrights/openexr/ChangeLog \
    trunk/Source/OpenEXR/Copyrights/openexr/INSTALL \
    trunk/Source/OpenEXR/Copyrights/openexr/LICENSE \
    trunk/Source/OpenEXR/Copyrights/openexr/NEWS \
    trunk/Source/OpenEXR/Copyrights/openexr/PATENTS \
    trunk/Source/OpenEXR/Copyrights/openexr/README \
    trunk/Source/OpenEXR/Copyrights/openexr/README.CVS \
    trunk/Source/OpenEXR/Copyrights/openexr/README.OSX \
    trunk/Source/OpenEXR/Copyrights/openexr/README.git \
    trunk/Source/OpenEXR/Copyrights/openexr/README.namespacing \
    trunk/Source/OpenEXR/Copyrights/openexr/README.win32 \
    trunk/Source/ZLib/ChangeLog \
    trunk/Source/ZLib/FAQ \
    trunk/Source/ZLib/INDEX \
    trunk/Source/ZLib/README \
    trunk/Source/ZLib/configure \
    trunk/Source/ZLib/zlib.3 \
    trunk/TestAPI/Test.2017.sln \
    trunk/TestAPI/exif.jpg \
    trunk/TestAPI/exif.jxr \
    trunk/TestAPI/sample.png \
    trunk/Wrapper/Delphi/_clean.bat \
    trunk/Wrapper/Delphi/demo/ImagePreview/ImagePreview.dpr \
    trunk/Wrapper/Delphi/demo/ImagePreview/ImagePreview.res \
    trunk/Wrapper/Delphi/demo/ImagePreview/MainFrm.dfm \
    trunk/Wrapper/Delphi/demo/ImagePreview/MainFrm.pas \
    trunk/Wrapper/Delphi/demo/ImagePreview/Tiger.jpg \
    trunk/Wrapper/Delphi/demo/MultiBitmap/MultiBitmap.dpr \
    trunk/Wrapper/Delphi/demo/MultiBitmap/MultiBitmap.res \
    trunk/Wrapper/Delphi/demo/MultiBitmap/MultiBitmap.stat \
    trunk/Wrapper/Delphi/demo/MultiBitmap/mbMainForm.dfm \
    trunk/Wrapper/Delphi/demo/MultiBitmap/mbMainForm.pas \
    trunk/Wrapper/Delphi/demo/TargaUnit/TargaImage.pas \
    trunk/Wrapper/Delphi/demo/WinBitmap/MainDemo.dpr \
    trunk/Wrapper/Delphi/demo/WinBitmap/MainDemo.res \
    trunk/Wrapper/Delphi/demo/WinBitmap/MainForm.dfm \
    trunk/Wrapper/Delphi/demo/WinBitmap/MainForm.pas \
    trunk/Wrapper/Delphi/src/FreeBitmap.pas \
    trunk/Wrapper/Delphi/src/FreeImage.pas \
    trunk/Wrapper/Delphi/src/FreeUtils.pas \
    trunk/Wrapper/Delphi/src/Version.inc \
    trunk/Wrapper/FreeImage.NET/cpp/FreeImageIO/FreeImageIO.Net.vcproj \
    trunk/Wrapper/FreeImage.NET/cpp/FreeImageIO/FreeImageIO.sln \
    trunk/Wrapper/FreeImage.NET/cpp/FreeImageIO/app.ico \
    trunk/Wrapper/FreeImage.NET/cs/Bin/delete.me \
    trunk/Wrapper/FreeImage.NET/cs/Doc/3.11.0/FreeImage.NET.shfbproj \
    trunk/Wrapper/FreeImage.NET/cs/Doc/3.12.0/FreeImage.NET.shfbproj \
    trunk/Wrapper/FreeImage.NET/cs/Doc/3.13.0/FreeImage.NET.shfbproj \
    trunk/Wrapper/FreeImage.NET/cs/Doc/FreeImage.NET.shfbproj \
    trunk/Wrapper/FreeImage.NET/cs/FreeImage.NET.nunit \
    trunk/Wrapper/FreeImage.NET/cs/FreeImage.NET.sln \
    trunk/Wrapper/FreeImage.NET/cs/Library/Classes/FreeImageBitmap.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Classes/FreeImageEngine.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Classes/FreeImagePlugin.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Classes/FreeImageStreamIO.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Classes/GifInformation.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Classes/ImageMetadata.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Classes/LocalPlugin.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Classes/MemoryArray.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Classes/MetadataModel.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Classes/MetadataModels.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Classes/MetadataTag.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Classes/Palette.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Classes/PluginRepository.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Classes/Scanline.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Classes/StreamWrapper.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Delegates.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/DisposalMethodType.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/FREE_IMAGE_COLOR_CHANNEL.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/FREE_IMAGE_COLOR_DEPTH.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/FREE_IMAGE_COLOR_OPTIONS.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/FREE_IMAGE_COLOR_TYPE.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/FREE_IMAGE_COMPARE_FLAGS.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/FREE_IMAGE_DITHER.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/FREE_IMAGE_FILTER.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/FREE_IMAGE_FORMAT.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/FREE_IMAGE_JPEG_OPERATION.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/FREE_IMAGE_LOAD_FLAGS.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/FREE_IMAGE_MDMODEL.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/FREE_IMAGE_MDTYPE.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/FREE_IMAGE_METADATA_COPY.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/FREE_IMAGE_QUANTIZE.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/FREE_IMAGE_SAVE_FLAGS.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/FREE_IMAGE_TMO.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/FREE_IMAGE_TYPE.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/ICC_FLAGS.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Enumerations/MD_SEARCH_FLAGS.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/FreeImageStaticImports.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/FreeImageWrapper.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Library.2005.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Library/Library.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Library/Properties/AssemblyInfo.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/BITMAP.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/BITMAPINFO.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/BITMAPINFOHEADER.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/FI16RGB555.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/FI16RGB565.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/FI1BIT.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/FI4BIT.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/FIBITMAP.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/FICOMPLEX.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/FIICCPROFILE.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/FIMEMORY.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/FIMETADATA.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/FIMULTIBITMAP.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/FIRGB16.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/FIRGBA16.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/FIRGBAF.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/FIRGBF.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/FIRational.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/FITAG.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/FIURational.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/FreeImageIO.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/Plugin.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/RGBQUAD.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/RGBTRIPLE.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/Structs/fi_handle.cs \
    trunk/Wrapper/FreeImage.NET/cs/Library/build.bat \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 01 - Loading and saving/Program.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 01 - Loading and saving/Properties/AssemblyInfo.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 01 - Loading and saving/Sample 01 - Loading and saving.2005.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 01 - Loading and saving/Sample 01 - Loading and saving.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 01 - Loading and saving/Sample.jpg \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 02 - Multipaged bitmaps/Program.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 02 - Multipaged bitmaps/Properties/AssemblyInfo.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 02 - Multipaged bitmaps/Sample 02 - Multipaged bitmaps.2005.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 02 - Multipaged bitmaps/Sample 02 - Multipaged bitmaps.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 02 - Multipaged bitmaps/multipaged.tif \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 03 - Allocating/Program.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 03 - Allocating/Properties/AssemblyInfo.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 03 - Allocating/Sample 03 - Allocating.2005.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 03 - Allocating/Sample 03 - Allocating.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 04 - Getting bitmap informations/MainForm.Designer.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 04 - Getting bitmap informations/MainForm.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 04 - Getting bitmap informations/MainForm.resx \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 04 - Getting bitmap informations/Properties/AssemblyInfo.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 04 - Getting bitmap informations/Sample 04 - Getting bitmap informations.2005.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 04 - Getting bitmap informations/Sample 04 - Getting bitmap informations.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 05 - Working with pixels/Program.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 05 - Working with pixels/Properties/AssemblyInfo.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 05 - Working with pixels/Sample 05 - Working with pixels.2005.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 05 - Working with pixels/Sample 05 - Working with pixels.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 05 - Working with pixels/Sample.jpg \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 05 - Working with pixels/Sample.tif \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 06 - Converting/MainForm.Designer.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 06 - Converting/MainForm.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 06 - Converting/MainForm.resx \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 06 - Converting/Properties/AssemblyInfo.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 06 - Converting/Sample 06 - Converting.2005.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 06 - Converting/Sample 06 - Converting.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 06 - Converting/Sample.jpg \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 07 - ICC Profiles/Program.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 07 - ICC Profiles/Properties/AssemblyInfo.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 07 - ICC Profiles/Sample 07 - ICC Profiles.2005.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 07 - ICC Profiles/Sample 07 - ICC Profiles.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 07 - ICC Profiles/Sample.jpg \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 08 - Creating a plugin/Properties/AssemblyInfo.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 08 - Creating a plugin/Sample 08 - Creating a plugin.2005.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 08 - Creating a plugin/Sample 08 - Creating a plugin.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 08 - Creating a plugin/Sample.jpg \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 08 - Creating a plugin/SampleForm.Designer.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 08 - Creating a plugin/SampleForm.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 08 - Creating a plugin/SampleForm.resx \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 08 - Creating a plugin/SerializationPlugin.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 09 - Working with streams/Properties/AssemblyInfo.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 09 - Working with streams/Sample 09 - Working with streams.2005.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 09 - Working with streams/Sample 09 - Working with streams.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 09 - Working with streams/SampleForm.Designer.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 09 - Working with streams/SampleForm.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 09 - Working with streams/SampleForm.resx \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 10 - Metadata/MainForm.Designer.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 10 - Metadata/MainForm.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 10 - Metadata/MainForm.resx \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 10 - Metadata/Properties/AssemblyInfo.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 10 - Metadata/Sample 10 - Metadata.2005.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 10 - Metadata/Sample 10 - Metadata.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 11 - Using the FreeImageBitmap class/MainForm.Designer.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 11 - Using the FreeImageBitmap class/MainForm.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 11 - Using the FreeImageBitmap class/MainForm.resx \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 11 - Using the FreeImageBitmap class/MetaDataFrame.Designer.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 11 - Using the FreeImageBitmap class/MetaDataFrame.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 11 - Using the FreeImageBitmap class/MetaDataFrame.resx \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 11 - Using the FreeImageBitmap class/Properties/AssemblyInfo.cs \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 11 - Using the FreeImageBitmap class/Sample 11 - Using the FreeImageBitmap class.2005.csproj \
    trunk/Wrapper/FreeImage.NET/cs/Samples/Sample 11 - Using the FreeImageBitmap class/Sample 11 - Using the FreeImageBitmap class.csproj \
    trunk/Wrapper/FreeImage.NET/cs/SourceFileMerger/FreeImage.cs.template \
    trunk/Wrapper/FreeImage.NET/cs/SourceFileMerger/Program.cs \
    trunk/Wrapper/FreeImage.NET/cs/SourceFileMerger/Properties/AssemblyInfo.cs \
    trunk/Wrapper/FreeImage.NET/cs/SourceFileMerger/SourceFileMerger.2005.csproj \
    trunk/Wrapper/FreeImage.NET/cs/SourceFileMerger/SourceFileMerger.csproj \
    trunk/Wrapper/FreeImage.NET/cs/UnitTest/FreeImage.cs \
    trunk/Wrapper/FreeImage.NET/cs/UnitTest/ImageManager.cs \
    trunk/Wrapper/FreeImage.NET/cs/UnitTest/Properties/AssemblyInfo.cs \
    trunk/Wrapper/FreeImage.NET/cs/UnitTest/UnitTest.2005.csproj \
    trunk/Wrapper/FreeImage.NET/cs/UnitTest/UnitTest.cs \
    trunk/Wrapper/FreeImage.NET/cs/UnitTest/UnitTest.csproj \
    trunk/Wrapper/FreeImage.NET/cs/clean.bat \
    trunk/Wrapper/FreeImagePlus/FreeImagePlus.2017.sln \
    trunk/Wrapper/FreeImagePlus/clean.bat \
    trunk/Wrapper/FreeImagePlus/dist/delete.me \
    trunk/Wrapper/FreeImagePlus/doc/FreeImagePlus.dox \
    trunk/Wrapper/FreeImagePlus/doc/footer.html \
    trunk/Wrapper/FreeImagePlus/doc/freeimage.png \
    trunk/Wrapper/FreeImagePlus/doc/freeimagedoc.jpg \
    trunk/Wrapper/FreeImagePlus/doc/index.html \
    trunk/Wrapper/FreeImagePlus/test/fipTest.2017.sln \
    trunk/Wrapper/FreeImagePlus/test/test.jpg \
    trunk/Wrapper/FreeImagePlus/test/test.tif \
    trunk/Wrapper/VB6/src/MFreeImage.bas \
    trunk/clean.bat \
    trunk/clean.sh \
    trunk/fipMakefile.srcs \
    trunk/genfipsrclist.sh \
    trunk/gensrclist.sh

HEADERS += \
    trunk/Examples/Generic/FIIO_Mem.h \
    trunk/Examples/OpenGL/TextureManager/TextureManager.h \
    trunk/Examples/Plugin/PluginCradle.h \
    trunk/FreeImage.rc \
    trunk/Source/CacheFile.h \
    trunk/Source/FreeImage.h \
    trunk/Source/FreeImageIO.h \
    trunk/Source/LibPNG/libpng.3 \
    trunk/Source/LibPNG/libpngpf.3 \
    trunk/Source/LibPNG/png.h \
    trunk/Source/LibPNG/pngconf.h \
    trunk/Source/LibPNG/pngdebug.h \
    trunk/Source/LibPNG/pnginfo.h \
    trunk/Source/LibPNG/pnglibconf.h \
    trunk/Source/LibPNG/pngpriv.h \
    trunk/Source/LibPNG/pngstruct.h \
    trunk/Source/LibRawLite/internal/dcraw_defs.h \
    trunk/Source/LibRawLite/internal/dcraw_fileio_defs.h \
    trunk/Source/LibRawLite/internal/defines.h \
    trunk/Source/LibRawLite/internal/dmp_include.h \
    trunk/Source/LibRawLite/internal/libraw_cameraids.h \
    trunk/Source/LibRawLite/internal/libraw_cxx_defs.h \
    trunk/Source/LibRawLite/internal/libraw_internal_funcs.h \
    trunk/Source/LibRawLite/internal/var_defines.h \
    trunk/Source/LibRawLite/internal/x3f_tools.h \
    trunk/Source/LibRawLite/libraw/libraw.h \
    trunk/Source/LibRawLite/libraw/libraw_alloc.h \
    trunk/Source/LibRawLite/libraw/libraw_const.h \
    trunk/Source/LibRawLite/libraw/libraw_datastream.h \
    trunk/Source/LibRawLite/libraw/libraw_internal.h \
    trunk/Source/LibRawLite/libraw/libraw_types.h \
    trunk/Source/LibRawLite/libraw/libraw_version.h \
    trunk/Source/LibTIFF4/t4.h \
    trunk/Source/LibTIFF4/tif_config.h \
    trunk/Source/LibTIFF4/tif_config.h.cmake.in \
    trunk/Source/LibTIFF4/tif_config.h.in \
    trunk/Source/LibTIFF4/tif_config.vc.h \
    trunk/Source/LibTIFF4/tif_config.wince.h \
    trunk/Source/LibTIFF4/tif_dir.h \
    trunk/Source/LibTIFF4/tif_fax3.h \
    trunk/Source/LibTIFF4/tif_predict.h \
    trunk/Source/LibTIFF4/tiff.h \
    trunk/Source/LibTIFF4/tiffconf.h \
    trunk/Source/LibTIFF4/tiffconf.h.cmake.in \
    trunk/Source/LibTIFF4/tiffconf.h.in \
    trunk/Source/LibTIFF4/tiffconf.vc.h \
    trunk/Source/LibTIFF4/tiffconf.wince.h \
    trunk/Source/LibTIFF4/tiffio.h \
    trunk/Source/LibTIFF4/tiffio.hxx \
    trunk/Source/LibTIFF4/tiffiop.h \
    trunk/Source/LibTIFF4/tiffvers.h \
    trunk/Source/LibTIFF4/uvcode.h \
    trunk/Source/LibWebP/src/dec/alphai_dec.h \
    trunk/Source/LibWebP/src/dec/common_dec.h \
    trunk/Source/LibWebP/src/dec/vp8_dec.h \
    trunk/Source/LibWebP/src/dec/vp8i_dec.h \
    trunk/Source/LibWebP/src/dec/vp8li_dec.h \
    trunk/Source/LibWebP/src/dec/webpi_dec.h \
    trunk/Source/LibWebP/src/dsp/common_sse2.h \
    trunk/Source/LibWebP/src/dsp/common_sse41.h \
    trunk/Source/LibWebP/src/dsp/dsp.h \
    trunk/Source/LibWebP/src/dsp/lossless.h \
    trunk/Source/LibWebP/src/dsp/lossless_common.h \
    trunk/Source/LibWebP/src/dsp/mips_macro.h \
    trunk/Source/LibWebP/src/dsp/msa_macro.h \
    trunk/Source/LibWebP/src/dsp/neon.h \
    trunk/Source/LibWebP/src/dsp/quant.h \
    trunk/Source/LibWebP/src/dsp/yuv.h \
    trunk/Source/LibWebP/src/enc/backward_references_enc.h \
    trunk/Source/LibWebP/src/enc/cost_enc.h \
    trunk/Source/LibWebP/src/enc/histogram_enc.h \
    trunk/Source/LibWebP/src/enc/vp8i_enc.h \
    trunk/Source/LibWebP/src/enc/vp8li_enc.h \
    trunk/Source/LibWebP/src/mux/animi.h \
    trunk/Source/LibWebP/src/mux/muxi.h \
    trunk/Source/LibWebP/src/utils/bit_reader_inl_utils.h \
    trunk/Source/LibWebP/src/utils/bit_reader_utils.h \
    trunk/Source/LibWebP/src/utils/bit_writer_utils.h \
    trunk/Source/LibWebP/src/utils/color_cache_utils.h \
    trunk/Source/LibWebP/src/utils/endian_inl_utils.h \
    trunk/Source/LibWebP/src/utils/filters_utils.h \
    trunk/Source/LibWebP/src/utils/huffman_encode_utils.h \
    trunk/Source/LibWebP/src/utils/huffman_utils.h \
    trunk/Source/LibWebP/src/utils/quant_levels_dec_utils.h \
    trunk/Source/LibWebP/src/utils/quant_levels_utils.h \
    trunk/Source/LibWebP/src/utils/random_utils.h \
    trunk/Source/LibWebP/src/utils/rescaler_utils.h \
    trunk/Source/LibWebP/src/utils/thread_utils.h \
    trunk/Source/LibWebP/src/utils/utils.h \
    trunk/Source/LibWebP/src/webp/decode.h \
    trunk/Source/LibWebP/src/webp/demux.h \
    trunk/Source/LibWebP/src/webp/encode.h \
    trunk/Source/LibWebP/src/webp/format_constants.h \
    trunk/Source/LibWebP/src/webp/mux.h \
    trunk/Source/LibWebP/src/webp/mux_types.h \
    trunk/Source/LibWebP/src/webp/types.h \
    trunk/Source/MapIntrospector.h \
    trunk/Source/Metadata/FIRational.h \
    trunk/Source/Metadata/FreeImageTag.h \
    trunk/Source/OpenEXR/Half/eLut.h \
    trunk/Source/OpenEXR/Half/half.h \
    trunk/Source/OpenEXR/Half/halfExport.h \
    trunk/Source/OpenEXR/Half/halfFunction.h \
    trunk/Source/OpenEXR/Half/halfLimits.h \
    trunk/Source/OpenEXR/Half/toFloat.h \
    trunk/Source/OpenEXR/Iex/Iex.h \
    trunk/Source/OpenEXR/Iex/IexBaseExc.h \
    trunk/Source/OpenEXR/Iex/IexErrnoExc.h \
    trunk/Source/OpenEXR/Iex/IexExport.h \
    trunk/Source/OpenEXR/Iex/IexForward.h \
    trunk/Source/OpenEXR/Iex/IexMacros.h \
    trunk/Source/OpenEXR/Iex/IexMathExc.h \
    trunk/Source/OpenEXR/Iex/IexNamespace.h \
    trunk/Source/OpenEXR/Iex/IexThrowErrnoExc.h \
    trunk/Source/OpenEXR/IexMath/IexMathFloatExc.h \
    trunk/Source/OpenEXR/IexMath/IexMathFpu.h \
    trunk/Source/OpenEXR/IexMath/IexMathIeeeExc.h \
    trunk/Source/OpenEXR/IlmBaseConfig.h \
    trunk/Source/OpenEXR/IlmImf/ImfAcesFile.h \
    trunk/Source/OpenEXR/IlmImf/ImfArray.h \
    trunk/Source/OpenEXR/IlmImf/ImfAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfAutoArray.h \
    trunk/Source/OpenEXR/IlmImf/ImfB44Compressor.h \
    trunk/Source/OpenEXR/IlmImf/ImfBoxAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfCRgbaFile.h \
    trunk/Source/OpenEXR/IlmImf/ImfChannelList.h \
    trunk/Source/OpenEXR/IlmImf/ImfChannelListAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfCheckedArithmetic.h \
    trunk/Source/OpenEXR/IlmImf/ImfChromaticities.h \
    trunk/Source/OpenEXR/IlmImf/ImfChromaticitiesAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfCompositeDeepScanLine.h \
    trunk/Source/OpenEXR/IlmImf/ImfCompression.h \
    trunk/Source/OpenEXR/IlmImf/ImfCompressionAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfCompressor.h \
    trunk/Source/OpenEXR/IlmImf/ImfConvert.h \
    trunk/Source/OpenEXR/IlmImf/ImfDeepCompositing.h \
    trunk/Source/OpenEXR/IlmImf/ImfDeepFrameBuffer.h \
    trunk/Source/OpenEXR/IlmImf/ImfDeepImageState.h \
    trunk/Source/OpenEXR/IlmImf/ImfDeepImageStateAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfDeepScanLineInputFile.h \
    trunk/Source/OpenEXR/IlmImf/ImfDeepScanLineInputPart.h \
    trunk/Source/OpenEXR/IlmImf/ImfDeepScanLineOutputFile.h \
    trunk/Source/OpenEXR/IlmImf/ImfDeepScanLineOutputPart.h \
    trunk/Source/OpenEXR/IlmImf/ImfDeepTiledInputFile.h \
    trunk/Source/OpenEXR/IlmImf/ImfDeepTiledInputPart.h \
    trunk/Source/OpenEXR/IlmImf/ImfDeepTiledOutputFile.h \
    trunk/Source/OpenEXR/IlmImf/ImfDeepTiledOutputPart.h \
    trunk/Source/OpenEXR/IlmImf/ImfDoubleAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfDwaCompressor.h \
    trunk/Source/OpenEXR/IlmImf/ImfDwaCompressorSimd.h \
    trunk/Source/OpenEXR/IlmImf/ImfEnvmap.h \
    trunk/Source/OpenEXR/IlmImf/ImfEnvmapAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfExport.h \
    trunk/Source/OpenEXR/IlmImf/ImfFastHuf.h \
    trunk/Source/OpenEXR/IlmImf/ImfFloatAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfFloatVectorAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfForward.h \
    trunk/Source/OpenEXR/IlmImf/ImfFrameBuffer.h \
    trunk/Source/OpenEXR/IlmImf/ImfFramesPerSecond.h \
    trunk/Source/OpenEXR/IlmImf/ImfGenericInputFile.h \
    trunk/Source/OpenEXR/IlmImf/ImfGenericOutputFile.h \
    trunk/Source/OpenEXR/IlmImf/ImfHeader.h \
    trunk/Source/OpenEXR/IlmImf/ImfHuf.h \
    trunk/Source/OpenEXR/IlmImf/ImfIO.h \
    trunk/Source/OpenEXR/IlmImf/ImfInputFile.h \
    trunk/Source/OpenEXR/IlmImf/ImfInputPart.h \
    trunk/Source/OpenEXR/IlmImf/ImfInputPartData.h \
    trunk/Source/OpenEXR/IlmImf/ImfInputStreamMutex.h \
    trunk/Source/OpenEXR/IlmImf/ImfInt64.h \
    trunk/Source/OpenEXR/IlmImf/ImfIntAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfKeyCode.h \
    trunk/Source/OpenEXR/IlmImf/ImfKeyCodeAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfLineOrder.h \
    trunk/Source/OpenEXR/IlmImf/ImfLineOrderAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfLut.h \
    trunk/Source/OpenEXR/IlmImf/ImfMatrixAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfMisc.h \
    trunk/Source/OpenEXR/IlmImf/ImfMultiPartInputFile.h \
    trunk/Source/OpenEXR/IlmImf/ImfMultiPartOutputFile.h \
    trunk/Source/OpenEXR/IlmImf/ImfMultiView.h \
    trunk/Source/OpenEXR/IlmImf/ImfName.h \
    trunk/Source/OpenEXR/IlmImf/ImfNamespace.h \
    trunk/Source/OpenEXR/IlmImf/ImfOpaqueAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfOptimizedPixelReading.h \
    trunk/Source/OpenEXR/IlmImf/ImfOutputFile.h \
    trunk/Source/OpenEXR/IlmImf/ImfOutputPart.h \
    trunk/Source/OpenEXR/IlmImf/ImfOutputPartData.h \
    trunk/Source/OpenEXR/IlmImf/ImfOutputStreamMutex.h \
    trunk/Source/OpenEXR/IlmImf/ImfPartHelper.h \
    trunk/Source/OpenEXR/IlmImf/ImfPartType.h \
    trunk/Source/OpenEXR/IlmImf/ImfPixelType.h \
    trunk/Source/OpenEXR/IlmImf/ImfPizCompressor.h \
    trunk/Source/OpenEXR/IlmImf/ImfPreviewImage.h \
    trunk/Source/OpenEXR/IlmImf/ImfPreviewImageAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfPxr24Compressor.h \
    trunk/Source/OpenEXR/IlmImf/ImfRational.h \
    trunk/Source/OpenEXR/IlmImf/ImfRationalAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfRgba.h \
    trunk/Source/OpenEXR/IlmImf/ImfRgbaFile.h \
    trunk/Source/OpenEXR/IlmImf/ImfRgbaYca.h \
    trunk/Source/OpenEXR/IlmImf/ImfRle.h \
    trunk/Source/OpenEXR/IlmImf/ImfRleCompressor.h \
    trunk/Source/OpenEXR/IlmImf/ImfScanLineInputFile.h \
    trunk/Source/OpenEXR/IlmImf/ImfSimd.h \
    trunk/Source/OpenEXR/IlmImf/ImfStandardAttributes.h \
    trunk/Source/OpenEXR/IlmImf/ImfStdIO.h \
    trunk/Source/OpenEXR/IlmImf/ImfStringAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfStringVectorAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfSystemSpecific.h \
    trunk/Source/OpenEXR/IlmImf/ImfTestFile.h \
    trunk/Source/OpenEXR/IlmImf/ImfThreading.h \
    trunk/Source/OpenEXR/IlmImf/ImfTileDescription.h \
    trunk/Source/OpenEXR/IlmImf/ImfTileDescriptionAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfTileOffsets.h \
    trunk/Source/OpenEXR/IlmImf/ImfTiledInputFile.h \
    trunk/Source/OpenEXR/IlmImf/ImfTiledInputPart.h \
    trunk/Source/OpenEXR/IlmImf/ImfTiledMisc.h \
    trunk/Source/OpenEXR/IlmImf/ImfTiledOutputFile.h \
    trunk/Source/OpenEXR/IlmImf/ImfTiledOutputPart.h \
    trunk/Source/OpenEXR/IlmImf/ImfTiledRgbaFile.h \
    trunk/Source/OpenEXR/IlmImf/ImfTimeCode.h \
    trunk/Source/OpenEXR/IlmImf/ImfTimeCodeAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfVecAttribute.h \
    trunk/Source/OpenEXR/IlmImf/ImfVersion.h \
    trunk/Source/OpenEXR/IlmImf/ImfWav.h \
    trunk/Source/OpenEXR/IlmImf/ImfXdr.h \
    trunk/Source/OpenEXR/IlmImf/ImfZip.h \
    trunk/Source/OpenEXR/IlmImf/ImfZipCompressor.h \
    trunk/Source/OpenEXR/IlmImf/b44ExpLogTable.h \
    trunk/Source/OpenEXR/IlmImf/dwaLookups.h \
    trunk/Source/OpenEXR/IlmThread/IlmThread.h \
    trunk/Source/OpenEXR/IlmThread/IlmThreadExport.h \
    trunk/Source/OpenEXR/IlmThread/IlmThreadForward.h \
    trunk/Source/OpenEXR/IlmThread/IlmThreadMutex.h \
    trunk/Source/OpenEXR/IlmThread/IlmThreadNamespace.h \
    trunk/Source/OpenEXR/IlmThread/IlmThreadPool.h \
    trunk/Source/OpenEXR/IlmThread/IlmThreadSemaphore.h \
    trunk/Source/OpenEXR/Imath/ImathBox.h \
    trunk/Source/OpenEXR/Imath/ImathBoxAlgo.h \
    trunk/Source/OpenEXR/Imath/ImathColor.h \
    trunk/Source/OpenEXR/Imath/ImathColorAlgo.h \
    trunk/Source/OpenEXR/Imath/ImathEuler.h \
    trunk/Source/OpenEXR/Imath/ImathExc.h \
    trunk/Source/OpenEXR/Imath/ImathExport.h \
    trunk/Source/OpenEXR/Imath/ImathForward.h \
    trunk/Source/OpenEXR/Imath/ImathFrame.h \
    trunk/Source/OpenEXR/Imath/ImathFrustum.h \
    trunk/Source/OpenEXR/Imath/ImathFrustumTest.h \
    trunk/Source/OpenEXR/Imath/ImathFun.h \
    trunk/Source/OpenEXR/Imath/ImathGL.h \
    trunk/Source/OpenEXR/Imath/ImathGLU.h \
    trunk/Source/OpenEXR/Imath/ImathHalfLimits.h \
    trunk/Source/OpenEXR/Imath/ImathInt64.h \
    trunk/Source/OpenEXR/Imath/ImathInterval.h \
    trunk/Source/OpenEXR/Imath/ImathLimits.h \
    trunk/Source/OpenEXR/Imath/ImathLine.h \
    trunk/Source/OpenEXR/Imath/ImathLineAlgo.h \
    trunk/Source/OpenEXR/Imath/ImathMath.h \
    trunk/Source/OpenEXR/Imath/ImathMatrix.h \
    trunk/Source/OpenEXR/Imath/ImathMatrixAlgo.h \
    trunk/Source/OpenEXR/Imath/ImathNamespace.h \
    trunk/Source/OpenEXR/Imath/ImathPlane.h \
    trunk/Source/OpenEXR/Imath/ImathPlatform.h \
    trunk/Source/OpenEXR/Imath/ImathQuat.h \
    trunk/Source/OpenEXR/Imath/ImathRandom.h \
    trunk/Source/OpenEXR/Imath/ImathRoots.h \
    trunk/Source/OpenEXR/Imath/ImathShear.h \
    trunk/Source/OpenEXR/Imath/ImathSphere.h \
    trunk/Source/OpenEXR/Imath/ImathVec.h \
    trunk/Source/OpenEXR/Imath/ImathVecAlgo.h \
    trunk/Source/OpenEXR/OpenEXRConfig.h \
    trunk/Source/Plugin.h \
    trunk/Source/Quantizers.h \
    trunk/Source/ToneMapping.h \
    trunk/Source/Utilities.h \
    trunk/Source/ZLib/crc32.h \
    trunk/Source/ZLib/deflate.h \
    trunk/Source/ZLib/gzguts.h \
    trunk/Source/ZLib/inffast.h \
    trunk/Source/ZLib/inffixed.h \
    trunk/Source/ZLib/inflate.h \
    trunk/Source/ZLib/inftrees.h \
    trunk/Source/ZLib/trees.h \
    trunk/Source/ZLib/zconf.h \
    trunk/Source/ZLib/zconf.h.in \
    trunk/Source/ZLib/zlib.h \
    trunk/Source/ZLib/zutil.h \
    trunk/Source/FreeImage/J2KHelper.h \
    trunk/Source/FreeImage/PSDParser.h \
    trunk/Source/FreeImageToolkit/Filters.h \
    trunk/Source/FreeImageToolkit/Resize.h \
    trunk/Source/LibJPEG/cderror.h \
    trunk/Source/LibJPEG/cdjpeg.h \
    trunk/Source/LibJPEG/jconfig.h \
    trunk/Source/LibJPEG/jdct.h \
    trunk/Source/LibJPEG/jerror.h \
    trunk/Source/LibJPEG/jinclude.h \
    trunk/Source/LibJPEG/jmemsys.h \
    trunk/Source/LibJPEG/jmorecfg.h \
    trunk/Source/LibJPEG/jpegint.h \
    trunk/Source/LibJPEG/jpeglib.h \
    trunk/Source/LibJPEG/jversion.h \
    trunk/Source/LibJPEG/transupp.h \
    trunk/Source/LibJXR/common/include/guiddef.h \
    trunk/Source/LibJXR/common/include/wmsal.h \
    trunk/Source/LibJXR/common/include/wmspecstring.h \
    trunk/Source/LibJXR/common/include/wmspecstrings_adt.h \
    trunk/Source/LibJXR/common/include/wmspecstrings_strict.h \
    trunk/Source/LibJXR/common/include/wmspecstrings_undef.h \
    trunk/Source/LibJXR/image/decode/decode.h \
    trunk/Source/LibJXR/image/encode/encode.h \
    trunk/Source/LibJXR/image/sys/ansi.h \
    trunk/Source/LibJXR/image/sys/common.h \
    trunk/Source/LibJXR/image/sys/perfTimer.h \
    trunk/Source/LibJXR/image/sys/strTransform.h \
    trunk/Source/LibJXR/image/sys/strcodec.h \
    trunk/Source/LibJXR/image/sys/windowsmediaphoto.h \
    trunk/Source/LibJXR/image/sys/xplatform_image.h \
    trunk/Source/LibJXR/image/x86/x86.h \
    trunk/Source/LibJXR/jxrgluelib/JXRGlue.h \
    trunk/Source/LibJXR/jxrgluelib/JXRMeta.h \
    trunk/Source/LibOpenJPEG/bio.h \
    trunk/Source/LibOpenJPEG/cidx_manager.h \
    trunk/Source/LibOpenJPEG/cio.h \
    trunk/Source/LibOpenJPEG/dwt.h \
    trunk/Source/LibOpenJPEG/event.h \
    trunk/Source/LibOpenJPEG/function_list.h \
    trunk/Source/LibOpenJPEG/image.h \
    trunk/Source/LibOpenJPEG/indexbox_manager.h \
    trunk/Source/LibOpenJPEG/invert.h \
    trunk/Source/LibOpenJPEG/j2k.h \
    trunk/Source/LibOpenJPEG/jp2.h \
    trunk/Source/LibOpenJPEG/mct.h \
    trunk/Source/LibOpenJPEG/mqc.h \
    trunk/Source/LibOpenJPEG/openjpeg.h \
    trunk/Source/LibOpenJPEG/opj_clock.h \
    trunk/Source/LibOpenJPEG/opj_codec.h \
    trunk/Source/LibOpenJPEG/opj_config.h \
    trunk/Source/LibOpenJPEG/opj_config_private.h \
    trunk/Source/LibOpenJPEG/opj_includes.h \
    trunk/Source/LibOpenJPEG/opj_intmath.h \
    trunk/Source/LibOpenJPEG/opj_inttypes.h \
    trunk/Source/LibOpenJPEG/opj_malloc.h \
    trunk/Source/LibOpenJPEG/opj_stdint.h \
    trunk/Source/LibOpenJPEG/pi.h \
    trunk/Source/LibOpenJPEG/raw.h \
    trunk/Source/LibOpenJPEG/t1.h \
    trunk/Source/LibOpenJPEG/t1_luts.h \
    trunk/Source/LibOpenJPEG/t2.h \
    trunk/Source/LibOpenJPEG/tcd.h \
    trunk/Source/LibOpenJPEG/tgt.h \
    trunk/TestAPI/TestSuite.h \
    trunk/Wrapper/FreeImage.NET/cpp/FreeImageIO/FreeImageIO.Net.h \
    trunk/Wrapper/FreeImage.NET/cpp/FreeImageIO/Stdafx.h \
    trunk/Wrapper/FreeImage.NET/cpp/FreeImageIO/app.rc \
    trunk/Wrapper/FreeImage.NET/cpp/FreeImageIO/resource.h \
    trunk/Wrapper/FreeImagePlus/FreeImagePlus.h \
    trunk/Wrapper/FreeImagePlus/FreeImagePlus.rc \
    trunk/Wrapper/FreeImagePlus/test/fipTest.h

